IMAGE_NAME = "bento/ubuntu-16.04"
N = 1
# Vagrant.actions[:start].delete(Vagrant::Action::VM::ShareFolders)

Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"

    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 1}"
            node.vm.hostname = "node-#{i}"
        end
    end
end

