apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  selector:
    matchLabels:
      app: angular
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: angular
        tier: frontend
    spec:
      containers:
      - image: amin0894/front:latest
        name: angular
        ports:
        - containerPort: 80
#        command: [ "/bin/sh","-c","cat /etc/nginx/nginx.conf" ]

        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: ./nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: confnginx
#        volumeMounts:
#        - name: angular-persistent-storage
#          mountPath: /var/www/html
#      volumes:
#      - name: angular-persistent-storage
#        persistentVolumeClaim:
#          claimName: wp-pv-claim

