apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment

spec:
  selector:
    matchLabels:
      app: mongoapp
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      name: mongodb-deployment

      labels:
        app: mongoapp
        tier: db
    spec:
      containers:
      - image: mongo:latest
        ports:
        - containerPort: 27017

#        volumeMounts:
#        - name: mongo-persistent-storage
#          mountPath: /var/www/html
#      volumes:
#      - name: mongo-persistent-storage
#        persistentVolumeClaim:
