apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        tier: db
    spec:
      containers:
      - image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017

#        volumeMounts:
#        - name: mongo-persistent-storage
#          mountPath: /var/www/html
#      volumes:
#      - name: mongo-persistent-storage
#        persistentVolumeClaim:
