apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30002
  selector:
    app: mongo
    tier: db
  type: NodePort